version: '3.8'

services:
  frontend:
    build:
      context: ./content-creator-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./content-creator-app:/app
      - /app/node_modules

  backend:
    build:
      context: ./content-creator-app-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/content-creator
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - ./content-creator-app-back:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: